server:
  port: 8995

logging:
  level:
    # 开启sql日志
    com.dao: DEBUG
    com: debug

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      url: jdbc:mysql://rm-bp1fwzre35glw0872o.mysql.rds.aliyuncs.com/auro_oa?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=Hongkong
      #      username: root
      #      password: AuroBubu2019!
      url: jdbc:mysql://124.70.157.93/liangshi?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=Hongkong
      username: dbls
      password: 123456t
      filters: stat,wall,log4j ,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
#filepath: /Users/wuqirong/Desktop/xmciq
filepath: C:\Users\dell\Desktop\xmciq
movepath: C:\Users\dell\Desktop\xmciq\xmciq
# 吨比例
tonRatio: 1